version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: studypulse
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin@123
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: 
      context: ./study-pulse-server
      dockerfile: Dockerfile
    command: gunicorn studypulse.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://root:admin@123@db:5432/studypulse

volumes:
  pgdata:
